name: Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PACKAGE_DIR_NAME: sphinx_automagicdoc
  PACKAGE_NAME: sphinx-automagicdoc

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip wheel build twine
      - name: Install the package
        run: pip install ".[doc]"
      - name: Build documentation
        run: spinx-autopyproject-build -b html doc doc/_build
      - name: Setup Pages
        if: ${{ !env.ACT }}
        uses: actions/configure-pages@v2
      - name: Upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'doc/_build'
      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v1
