name: Documentation

on:
  push:
    branches: [ $default-branch ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip wheel
      - name: Install the package
        run: pip install ".[doc]"
      - name: Build documentation
        run: spinx-autopyproject-build -b html doc doc/_build
      - name: Setup Pages
        if: !env.ACT
        uses: actions/configure-pages@v2
      - name: Upload artifact
        if: !env.ACT
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'doc/_build'
      - name: Deploy to GitHub Pages
        if: !env.ACT
        id: deployment
        uses: actions/deploy-pages@v1
