name: Python testing

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip wheel
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/sphinx-autopyproject
          path: sphinx-autopyproject
      - name: Install dev version of sphinx-autopyproject
        run: pip install ./sphinx-autopyproject
      - name: Install the package
        run: pip install ".[doc]"
      - name: Build documentation
        run: spinx-autopyproject-build -b html doc doc/_build
      - name: List files
        shell: python
        run: |
          from pathlib import Path
          print("\n".join(map(str, Path("doc/_build").rglob("**/*"))))
      - name: Check existence of some result
        shell: python
        run: |
          from pathlib import Path
          raise SystemExit(not Path("doc/_build/sphinx_automagicdoc.html").exists())
